const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "../content/education");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".html")).sort();

files.forEach((file) => {
  const base = file.replace(".html", "");
  const htmlPath = path.join(dir, file);
  const tsPath = path.join(dir, base + ".ts");
  const content = fs.readFileSync(htmlPath, "utf8");

  const output =
    "// Auto-generated from " +
    file +
    " for Edge Runtime compatibility\nexport default " +
    JSON.stringify(content) +
    ";\n";
  fs.writeFileSync(tsPath, output);
  console.log("Converted", file, "to", base + ".ts");
});

// EducationalContent imports this index; update it in the same generation.
const locales = files.map((file) => file.replace(".html", ""));
fs.writeFileSync(path.join(dir, "index.ts"),
  "// Auto-generated by scripts/convert-html.js; edit the HTML sources.\n" +
  locales.map((locale) => `import ${locale} from "./${locale}";`).join("\n") +
  "\nexport const educationContent: Record<string, string> = { " + locales.join(", ") + " };\n");
