// Auto-generated by scripts/convert-html.js; edit the HTML sources.
import de from "./de";
import en from "./en";
import es from "./es";
import fr from "./fr";
import ja from "./ja";
import ko from "./ko";
import pt from "./pt";
import ru from "./ru";
import zh from "./zh";
export const educationContent: Record<string, string> = { de, en, es, fr, ja, ko, pt, ru, zh };
